### ISSUE TITLE
Level 1: HTML - Video & Challenges

### ISSUE THREAD

**Issue by birdcar** [GeneralOutcast/generaloutcast.github.io#1]
## Objective: Watch Level 1

Note: Make sure to watch all of level one, there may be more than one video and set of challenges. 
### Stuff You'll Need
- Focus
- The video on the Code School site
### To-Do
- [x] What are you even waiting for, just [do it](http://i.giphy.com/104ueR8J1OPM2s.gif)
- [x] Continue on to assignment in issue #3 
- [x] Check this box, add the Finished label, and close this issue.

**Comment by birdcar** [comment]
@GeneralOutcast Did you finish these up? Just wanting to know where you're at. I'm gonna be adding a lot more today so that you can move at your own pace.

**Comment by sophanoph** [comment]
:+1:
