### ISSUE TITLE
Read the "Mastering Issues" Guide

### ISSUE THREAD

**Issue by birdcar** [GeneralOutcast/generaloutcast.github.io#2]
## Objective: Master Issues

Since most of our communication about your "homework" will take place here in the issues on this repository, you should probably know badass ways of using them, or at least know your way around them.
### Stuff You'll Need
1. Link to the guide: [Mastering Issues by GitHub](https://guides.github.com/features/issues/)
### To-do
- [x] Read the Guide
- [x] Change the label on this issue from "Assignment" to "Finished"
- [x] Comment on this issue with something smart-ass and emoji filled
- [x] Close the issue.

**Comment by sophanoph** [comment]
0 to :100:  real quick :clap:
