### ISSUE TITLE
Level 1: HTML - Homework

### ISSUE THREAD

**Issue by birdcar** [GeneralOutcast/generaloutcast.github.io#3]
## Objective: Start Building Your Website

Just to make sure that you're learning, and also to begin building the kick ass website that you'll be continually working on throughout your entire Code School path, we're gonna use some of that stuff you just learned in the real world.

Before you get started on the to-dos, take a minute and really think about the site. We're only building one page for now--and it's not going to look pretty just yet--so it's going to start out as a simple "About Me" page. The web is great because you can decide how you want people to perceive you. If you're being a douchebag you call this "branding", we're just gonna call it tone. The tone you use to introduce yourself to an old friend or one of your siblings it totally different than the tone you use to introduce yourself to someone who might hire you. You're in control of the tone of this page, so think about how you want to sound and be perceived.  

Start by thinking of a title, you can use a simple tone like **"About Me"**, a more formal (aka: boring) tone like **"About Sophia Cannariato"**, or a funny/sassy/accurate tone like **"Worship Me, Bitch."** :trollface: 

Once you've decided on a tone for your title, use that same tone for everything else you write on the page. This is me "grading" what you're doing, so you don't need to make this some sterile bullshit school project. 
### Stuff You'll Need
- **The information you learned on Code School in #1** -- _(download the slides if you need to)_
- **Your [index.html](https://github.com/GeneralOutcast/generaloutcast.github.io/blob/master/index.html) file** -- _This is the name of almost every homepage you'll ever make._
- **Google** -- _Google is your best friend and your worst enemy. On one hand, it's definitely the first thing that everyone does when they don't remember something, no matter how long they've been building web sites or apps. On the other hand, what do you do if you don't have the internet but you need to get something done? Try to only use it if necessary._
### To-do
- [x] **Title the page.** -- Make sure to make your title the most important content on the page, and also make sure to actually tell the web browser the page's title using the appropriate HTML tag (hint: the title should be written twice in index.html).
- [x] **Create a secondary section** -- Call it "Bio" or whatever equivalent subtitle matches the tone you selected.
- [x] **Write a 1 Paragraph Bio** -- 1 Paragraph = at least 6 sentences. Make it so that if someone never met you before they would learn something new about you and get an idea of your sense of humor or personality, not just your interests (we'll be doing those later).
- [x] **Create two lists** --  Make the lists about whatever you'd like, and they can be ordered or unordered. Favorite Bands, Favorite foods, Favorite Movies, People you wish would die, etc.
- [x] **Links Links Links Links** -- Go through your lists and create links to things. If you made a band list, link the names of the bands to their websites or twitter pages. If you made a list of concerts you want to go to, link to the ticket pages. 
- [x] **Check this box, add the "finished" label, and close this issue.

**Comment by sophanoph** [comment]
I just started and you want me to build a website?!

**Comment by sophanoph** [comment]
okay
okay
.....
i got this
:100:

**Comment by birdcar** [comment]
@GeneralOutcast: you know you got this. I didn't ask for rocket science, just for you to build some HTML. :shipit:

**Comment by birdcar** [comment]
@GeneralOutcast I added some stuff to index.html for you. Take a look at f8efbeeac9483524c662e122f9aabe72d318c0cf to see what I did and then you should be able to finish the rest of the assignment on your own.

**Comment by sophanoph** [comment]
i totally owned that bio :100: :dart: :facepunch:

**Comment by GeneralOutcast** [comment]
also i made the lists OLs because i liked it better that way
