### ISSUE TITLE
Level 2:CSS - Homework

### ISSUE THREAD

**Issue by birdcar** [GeneralOutcast/generaloutcast.github.io#5]
## Objective: Add some basic color and style to your page.

This is a _huge_ level and there's a ton of information thrown at you. Hopefully things are starting to make sense, and if they aren't Please don't hesitate to open an issue or comment on one of the assignments to let me know where you're stuck. 

This level is where you get introduced to CSS and gain a basic understanding of the syntax of that particular language. This one is a little more abstract than HTML, but still pretty fun. Just so you don't get overwhelmed in thinking about how to design your page just yet, I'm going to give you fairly specific things to do just so you can learn the ropes. As we go along this course, some of those instructions will become less specific and open to your own style and interpretation.

Feel free to use google if you have no idea what css command you need in order to accomplish a particular look.
### Stuff You'll Need
- The stuff you learned in the Level 2 Video & Challenges 
- Your index.html file.
- [imagination!](https://media.giphy.com/media/7OBf8i7L7sGkg/giphy.gif)
### To-Do
- [x] Use the [Coolors Browser](https://coolors.co/browser) to find a color palette that you like. 
- [x] Make a page in your Wiki titled "Style Guide" and Put all of the hexadecimal values for your color palette in it. 
- [x] Next to each hexadecimal value you just put in the wiki, name the color so you can remember what it is.
- [x] Create a `main.css` file in your repo using the new file button. make the first line in `main.css` say `# Awesome Styles go here` and commit the file with the message `Created main.css`
- [x] Link your new `main.css` file into your `index.html` page. Refer to the slides from code school if you don't remember how to do this, or google it. Once you finish commit the changes with the comment `linked main stylesheet`
- [x] Create a selector in `main.css` that will change the color of your H1 text to match a color in your color palette
- [x] Create a selector in `main.css` that will change the color of your H2 text to match your H1 
- [x] Take a second and look over the CSS code you've made so far. Is there a way to combine those selectors to make your life easier? Google around if you need help.
- [x] Center your H1 text on the page.
- [x] Make it so your H2 tags are underlined
- [x] commit your changes to `main.css` with the comment "prettified text things :rainbow:"
- [x] Go get a drink of water and wait a few minutes, then visit http://generaloutcast.github.io and look at your changes. Did everything work like you wanted it to? Create an issue and reference this issue if it didn't. If it did, congrats! You did it!
- [x] Remember your video talking about something called "the box model"? Write a page in the wiki describing the difference between margin and padding, and talking about when you'd use them. It doesn't need to be long, but trust me when I say that those are super confusing and being able to refer back to that page will be helpful.
- [x] Check this box, add the "Finished" label, and close this issue.

**Comment by birdcar** [comment]
@GeneralOutcast Hey, I'm headed out for lunch. You good? Need any help?

**Comment by sophanoph** [comment]
@nickcannariato yeahh i have no idea what i'm doing so..

**Comment by birdcar** [comment]
@GeneralOutcast You can wait till I get back at the end of the month or you can just keep trying stuff till you figure it out slash also check google for how to do things.

**Comment by sophanoph** [comment]
@nickcannariato yeah okay cool. I'll probally figure it out. :+1:
