### ISSUE TITLE
Assignment: Get Set Up at FreeCodeCamp

### ISSUE THREAD

**Issue by birdcar** [GeneralOutcast/generaloutcast.github.io#9]
I want to get you set at free code camp so you can start building a portfolio and learning at your own pace on their system
## Todo
- [ ] Set up an account at http://www.freecodecamp.com/
- [ ] Go through the set-up tutorial.
- [ ] Complete the HTML and CSS sections. Open issues if you get stuck and get involved in their gitter chat room as well.
